"""経費に事業按分率(business_ratio)を追加

Revision ID: 2a636a55d5b5
Revises: 7f9328d2982e
Create Date: 2026-06-22 16:09:35.147620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a636a55d5b5'
down_revision: Union[str, None] = '7f9328d2982e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('business_ratio', sa.Integer(), server_default='100', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'business_ratio')
    # ### end Alembic commands ###
