"""収入に源泉徴収税額(withholding)を追加

Revision ID: aebe6680287f
Revises: 2ad1ce5881c3
Create Date: 2026-07-06 12:02:58.076262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebe6680287f'
down_revision: Union[str, None] = '2ad1ce5881c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('withholding', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'withholding')
    # ### end Alembic commands ###
